# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    container_name: app
    restart: "no"
    build: .
    expose:
    - "8080"
    ports:
    - "8080:8080"
    environment:
    - DB_URL=postgresql://FiestaUser:FiestaPassword@db:5432/Fiesta
    - secret=sldjfhsdkisdv
    links:
    - "db:db"

  db:
    image: postgres
    environment:
      POSTGRES_USER: FiestaUser
      POSTGRES_PASSWORD: FiestaPassword
      POSTGRES_DB: Fiesta
    expose:
    - "5432"