# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    container_name: app
    restart: "no"
    build: .
    expose:
    - "8080"
    environment:
    - DB_URL=postgresql://CarnetUser:CarnetPassword@db:5432/Carnet
    - secret=sldjfhsdkisdv
    links:
    - "db:db"

  db:
    image: postgres
    environment:
      POSTGRES_USER: CarnetUser
      POSTGRES_PASSWORD: CarnetPassword
      POSTGRES_DB: Carnet
    expose:
    - "5432"